### ISSUE TITLE
Not working, help...

### ISSUE THREAD

**Issue by SkybuckFlying** [Potherca/git-split-file#5] opened 2018-06-30 18:58 UTC
On windows 7 I open Git Bash
script is installed, script starts up

Can't get it to work:

 The given split file '/s/Delphi/Applications/PascalCoin/Try restructure skybuck style/Try split file script/Molina.txt' is not part of a git repository

this file *IS* added to a repository so what does it show this error message ???

**Comment by Potherca** [comment] 2018-07-03 23:06
There is a bug in the script that I still need to resolve. I've got a fix lying around somewhere but thus far I have not been able to find the time to implement more tests and add the fix.

I'll try to allocate some time to fixing these issues so you at least have a fighting chance of the script working as advertised 👍

**Comment by Potherca** [comment] 2018-07-03 23:07
Issue caused by same bug as described in #2

**Comment by SkybuckFlying** [comment] 2018-07-04 09:15
Thank you for replieing to my requests for help.

Meanwhile I have read up about GIT, thought about it some more and I think I am starting to understand, what GIT CAN and CANNOT do.

Now that my understanding is a little bit better, and ofcourse also thanks to your tricks, very inspiring, I will try some more methods, to try and reproduce what your script claims to do ;) but also maybe I can take it even much further haha, that be cool. The road to success is filled with many failures, I will not be surprised if my new ideas are not as GIT successfull as I hoped, in that case I will have to fall back on your script(s). So by all means do get that bug out ! =D

I will keep you informed if I find new paths of GIT success ! =D until then, peace out ! =D

**Comment by SkybuckFlying** [comment] 2018-07-04 09:18
Oh I forgot the link, I wanted to show you something in case you haven't seen it yet.

I found the information on this link most inspiring and clearifieing:

http://eagain.net/articles/git-for-computer-scientists/

**Comment by Potherca** [comment] 2018-07-22 21:28
Issue _should_ be fixed with release `v0.2.0`

**Closed as completed by Potherca** 2018-07-22 21:28 UTC
Labels: duplicate
